#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

if [ -z "$SSH_AUTH_SOCK" ]; then
    eval "$(ssh-agent -s)"
fi

xmodmap "$HOME"/.xmodmap
xcape -e 'Mode_switch=Escape'
xbacklight -set 100
xset s off
xset -dpms
xset r rate 200 50

eval "$(dbus-launch --sh-syntax)"

exec herbstluftwm --locked
