#!/usr/bin/env zsh

export EDITOR=nvim

export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_RUNTIME_DIR="$PREFIX/run/user/$(id -u)"

export SYSTEMD_COLORS=true
export SYSTEMD_PAGER="nvim +Man!"

export MANPAGER="nvim +Man!"
export PAGER="nvim +Man!"

export BROWSER="firefox"

export ANSIBLE_CONFIG="$XDG_CONFIG_HOME"/ansible/ansible.cfg
export ANSIBLE_HOME="$XDG_CONFIG_HOME"/ansible

export GPG_TTY=$(tty)

export GNUPGHOME="$XDG_DATA_HOME"/gnupg

export PASSWORD_STORE_DIR="$XDG_DATA_HOME"/pass

export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc

export GOPATH="$XDG_DATA_HOME/go"
export GOBIN="$GOPATH/bin"

export JDTLS_JVM_ARGS="-javaagent:$HOME/.m2/repository/org/projectlombok/lombok/1.18.22/lombok-1.18.22.jar"

export PYENV_ROOT="$XDG_DATA_HOME/pyenv"

export CARGO_HOME="$XDG_DATA_HOME"/cargo
export CARGO_BIN="$CARGO_HOME"/bin

export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker

export LESSHISTFILE="$XDG_CACHE_HOME"/less/history

export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history

export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc

export PYENV_ROOT="$XDG_DATA_HOME"/pyenv

export RUSTUP_HOME="$XDG_DATA_HOME"/rustup

export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages

export ZIM_HOME="$XDG_CACHE_HOME"/zim

export STARSHIP_CONFIG=$HOME/.config/starship/config.toml

export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS' --color=fg:#c5cac5,bg:#293329,hl:#5f87af --color=fg+:#c5cac5,bg+:#4c664c,hl+:#5fd7ff --color=info:#afaf87,prompt:#d7005f,pointer:#d7005f --color=marker:#87ff00,spinner:#af5fff,header:#87afaf'

export FZF_MARKS_FILE="$XDG_CONFIG_HOME"/fzf-marks/marks-file

export SKIM_DEFAULT_OPTIONS=$SKIM_DEFAULT_OPTIONS' --color=fg:#c5cac5,bg:#293329,hl:#5f87af,fg+:#c5cac5,bg+:#4c664c,hl+:#5fd7ff,info:#afaf87,prompt:#d7005f,pointer:#d7005f,marker:#87ff00,spinner:#af5fff,header:#87afaf'

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"

export AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME"/aws/credentials
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME"/aws/config

export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority

export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc

export ANDROID_HOME="$XDG_DATA_HOME"/android

export GEM_HOME="$XDG_DATA_HOME"/gem
export GEM_SPEC_CACHE="$XDG_CACHE_HOME"/gem

export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle

export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"

export MYSQL_HISTFILE="$XDG_DATA_HOME"/mysql_history

export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history
export PSQL_HISTORY="$XDG_DATA_HOME/psql_history"

export SQLITE_HISTORY="$XDG_CACHE_HOME"/sqlite_history

export WINEPREFIX="$XDG_DATA_HOME"/wine

export FZF_DEFAULT_OPTS=" \
--color=bg+:#293329,bg:#3e4d3e,spinner:#f2d5cf,hl:#e78284 \
--color=fg:#c6d0f5,header:#e78284,info:#ca9ee6,pointer:#f2d5cf \
--color=marker:#f2d5cf,fg+:#c6d0f5,prompt:#ca9ee6,hl+:#e78284"

# path
typeset -U path PATH
path+=("$path[@]")
path+=("$HOME/.local/bin")
path+=("$HOME/.krew/bin")
path+=("./node_modules/.bin")
path+=("$GOBIN")
path+=("$CARGO_BIN")
path+=("$PYENV_ROOT/bin")
export PATH
